name: spotidl
description: A spotify downloader

publish_to: 'none'


version: '0.0.3'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_explode_dart: ^1.10.8
  spotify: ^0.7.0
  permission_handler: ^8.3.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.11
  dart_tags: ^0.4.0
  ffmpeg_kit_flutter_audio: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/Spotify-F-DL.png

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/Spotify-F-DL.png'
