name: spotidl
description: A spotify downloader

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/Spotify-F-DL.png

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/Spotify-F-DL.png'
